### ISSUE TITLE
Feature Request: Player item log

### ISSUE THREAD

**Issue by JackaldaJester** [krbz999/backpack-manager#6]
Hello!

I think this module does a lot that I want. One feature I'd like to see, if possible (for DnD):
-Player's character name next to item they stash

I think this module would be great to use for a party stash, but my players are particular in what items are theirs when they put it in a stash. 

Thank you!

**Comment by Truncated** [comment]
Would be handy to have a field on each line item as well, so that you can remember where you got half of that stuff six months ago.

If the items are pulled from something like Item Piles enabled tokens in "loot the bodies" ways, would the source creature's name be added to the stash, or the player who "looted" the item?

**Comment by krbz999** [comment]
Thank you for enjoying this module, it means a lot, truly.

With container management becoming a core feature of the system as of dnd5e v3, this module will no longer be developed.
